services:
  nextcloud-db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
    volumes:
      - nextcloud_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  nextcloud:
    image: nextcloud:latest
    restart: always
    entrypoint: ["/docker-entrypoint-custom.sh"]
    command: ["apache2-foreground"]
    ports:
      - "8080:80"
    links:
      - nextcloud-db
    volumes:
      - nextcloud_data:/var/www/html
      - ./nextcloud-config.php:/tmp/custom-config.php:ro
      - ./docker-entrypoint-custom.sh:/docker-entrypoint-custom.sh:ro
    environment:
      MYSQL_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: nextcloud-db
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin123
      NEXTCLOUD_TRUSTED_DOMAINS: localhost
      # Disable rate limiting for testing
      BRUTE_FORCE_PROTECTION_MAX_ATTEMPTS: 999
      BRUTE_FORCE_PROTECTION_DELAY: 0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status.php"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      nextcloud-db:
        condition: service_healthy

volumes:
  nextcloud_db:
  nextcloud_data: