@startuml modules
FileWatcher --> FileController: WriteNotification(Filename)
FileController --> FileHandler: WriteNotification(timestamp)
FileHandler --> FileController: UploadNotification(Filename, timestamp)
@enduml